services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres-chatney
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chatney
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka
    ports:
      - '9092:9092'

  rustfs:
    image: rustfs/rustfs
    container_name: rustfs
    restart: unless-stopped
    ports:
      - "9000:9000" # AWS S3 API
      - "9001:9001" # Admin dashboard
    environment:
      RUSTFS_ACCESS_KEY: admin
      RUSTFS_SECRET_KEY: admin
    volumes:
      - rustfs_data:/data

volumes:
  rustfs_data:
    driver: local
  postgres_data:
    driver: local
