services:
  mongo:
    image: mongo:6
    container_name: mongodb-chatney
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongo_data:/data/db

  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=miniopass
      - MINIO_DEFAULT_BUCKETS=chatney

volumes:
  minio_data:
    driver: local
  mongo_data:
    driver: local
