services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres-chatney
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chatney
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql

  kafka:
    image: apache/kafka
    ports:
      - '9092:9092'

  rustfs:
    image: rustfs/rustfs:1.0.0
    container_name: rustfs
    restart: unless-stopped
    ports:
      - "9000:9000" # AWS S3 API
      - "9001:9001" # Admin dashboard
    environment:
      RUSTFS_ACCESS_KEY: admin
      RUSTFS_SECRET_KEY: admin
    volumes:
      - rustfs_data:/data

  rustfs-init:
    image: amazon/aws-cli:2.37.1
    depends_on:
      - rustfs
    restart: "no"
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: admin
      AWS_DEFAULT_REGION: us-east-1
    entrypoint: >
      /bin/sh -c '
      until aws --endpoint-url http://rustfs:9000 s3api list-buckets > /dev/null 2>&1; do sleep 1; done;
      aws --endpoint-url http://rustfs:9000 s3api head-bucket --bucket chatney 2>/dev/null
      || aws --endpoint-url http://rustfs:9000 s3api create-bucket --bucket chatney;
      aws --endpoint-url http://rustfs:9000 s3api put-bucket-policy --bucket chatney --policy "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"*\"]},\"Action\":[\"s3:GetObject\",\"s3:GetObjectTagging\",\"s3:ListBucket\",\"s3:GetBucketLocation\"],\"Resource\":[\"arn:aws:s3:::chatney/*\"]},{\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"arn:aws:iam::*:root\"]},\"Action\":[\"s3:PutObject\",\"s3:DeleteObject\",\"s3:PutObjectTagging\",\"s3:DeleteObjectTagging\"],\"Resource\":[\"arn:aws:s3:::chatney/*\"]}]}"
      '

volumes:
  rustfs_data:
    driver: local
  postgres_data:
    driver: local
