package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"chatney-backend/graph"
	"chatney-backend/graph/model"
	"chatney-backend/src/domains/permissions"
	"context"
)

// GetPermissionsList is the resolver for the getPermissionsList field.
func (r *queryResolver) GetPermissionsList(ctx context.Context) (*model.PermissionsListReturn, error) {
	permissionsGroups, err := permissions.PermissionsGroups.GetPermissionsList()

	if err != nil {
		return nil, err
	}

	return &model.PermissionsListReturn{
		Groups: permissionsGroups,
	}, nil
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
