// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql_models

import (
	"fmt"
	"io"
	"strconv"
)

type Channel struct {
	ID            string `json:"Id"`
	Name          string `json:"Name"`
	ChannelTypeID string `json:"ChannelTypeId"`
	WorkspaceID   string `json:"WorkspaceId"`
}

type ChannelGroup struct {
	ID        string   `json:"Id"`
	Name      string   `json:"name"`
	Channels  []string `json:"channels"`
	Order     int32    `json:"order"`
	Workspace string   `json:"workspace"`
}

type ChannelRole struct {
	ChannelID string `json:"channelId"`
	RoleID    string `json:"roleId"`
}

type ChannelSettings struct {
	ChannelID       string `json:"channelId"`
	LastSeenMessage string `json:"lastSeenMessage"`
	Muted           bool   `json:"muted"`
}

type ChannelType struct {
	ID         string `json:"Id"`
	Label      string `json:"Label"`
	Key        string `json:"Key"`
	BaseRoleID string `json:"BaseRoleId"`
}

type ChannelTypeRole struct {
	ChannelTypeID string `json:"channelTypeId"`
	RoleID        string `json:"roleId"`
}

type CreateChannelGroupInput struct {
	Name      string   `json:"name"`
	Channels  []string `json:"channels"`
	Order     int32    `json:"order"`
	Workspace string   `json:"workspace"`
}

type CreateRoleDto struct {
	Name        string           `json:"Name"`
	Permissions []string         `json:"Permissions"`
	Settings    *RoleSettingsDto `json:"Settings"`
}

type CreateUserDto struct {
	Password   string     `json:"password"`
	Name       string     `json:"name"`
	Status     UserStatus `json:"status"`
	Email      string     `json:"email"`
	Workspaces []string   `json:"workspaces,omitempty"`
}

type EditRoleDto struct {
	ID          string           `json:"Id"`
	Name        string           `json:"Name"`
	Permissions []string         `json:"Permissions,omitempty"`
	Settings    *RoleSettingsDto `json:"Settings"`
}

type MutateChannelDto struct {
	Name          string `json:"Name"`
	ChannelTypeID string `json:"ChannelTypeId"`
	WorkspaceID   string `json:"WorkspaceId"`
}

type MutateChannelTypeDto struct {
	Label      string `json:"Label"`
	Key        string `json:"Key"`
	BaseRoleID string `json:"BaseRoleId"`
}

type MutateWorkspaceDto struct {
	Name string `json:"Name"`
}

type Mutation struct {
}

type PermissionsGroup struct {
	Label string   `json:"label"`
	List  []string `json:"list"`
}

type PermissionsListReturn struct {
	Groups []*PermissionsGroup `json:"groups"`
}

type Query struct {
}

type Role struct {
	ID          string        `json:"Id"`
	Name        string        `json:"Name"`
	Permissions []string      `json:"Permissions,omitempty"`
	Settings    *RoleSettings `json:"Settings"`
}

type RoleSettings struct {
	Base bool `json:"Base"`
}

type RoleSettingsDto struct {
	Base bool `json:"Base"`
}

type SystemConfigValue struct {
	Name  string `json:"Name"`
	Value string `json:"Value"`
	Type  string `json:"Type"`
}

type UpdateChannelGroupInput struct {
	ID       string   `json:"Id"`
	Name     *string  `json:"name,omitempty"`
	Channels []string `json:"channels,omitempty"`
	Order    *int32   `json:"order,omitempty"`
}

type UpdateUserDto struct {
	Name       string     `json:"name"`
	Status     UserStatus `json:"status"`
	Email      string     `json:"email"`
	Workspaces []string   `json:"workspaces,omitempty"`
}

type User struct {
	ID               string             `json:"id"`
	Name             string             `json:"name"`
	Status           UserStatus         `json:"status"`
	Email            string             `json:"email"`
	Roles            *UserRolesSettings `json:"roles"`
	ChannelsSettings []*ChannelSettings `json:"channelsSettings,omitempty"`
	Workspaces       []string           `json:"workspaces,omitempty"`
}

type UserRolesSettings struct {
	Global       *string            `json:"global,omitempty"`
	Workspace    []*WorkspaceRole   `json:"workspace,omitempty"`
	Channel      []*ChannelRole     `json:"channel,omitempty"`
	ChannelTypes []*ChannelTypeRole `json:"channel_types,omitempty"`
}

type Workspace struct {
	ID   string `json:"Id"`
	Name string `json:"Name"`
}

type WorkspaceRole struct {
	WorkspaceID string `json:"workspaceId"`
	RoleID      string `json:"roleId"`
}

type UserStatus string

const (
	UserStatusActive   UserStatus = "ACTIVE"
	UserStatusInactive UserStatus = "INACTIVE"
	UserStatusBanned   UserStatus = "BANNED"
	UserStatusMuted    UserStatus = "MUTED"
)

var AllUserStatus = []UserStatus{
	UserStatusActive,
	UserStatusInactive,
	UserStatusBanned,
	UserStatusMuted,
}

func (e UserStatus) IsValid() bool {
	switch e {
	case UserStatusActive, UserStatusInactive, UserStatusBanned, UserStatusMuted:
		return true
	}
	return false
}

func (e UserStatus) String() string {
	return string(e)
}

func (e *UserStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserStatus", str)
	}
	return nil
}

func (e UserStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
