// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql_models

type CreateRoleDto struct {
	Name        string           `json:"Name"`
	Permissions []string         `json:"Permissions"`
	Settings    *RoleSettingsDto `json:"Settings"`
}

type EditRoleDto struct {
	ID          string           `json:"Id"`
	Name        string           `json:"Name"`
	Permissions []string         `json:"Permissions,omitempty"`
	Settings    *RoleSettingsDto `json:"Settings"`
}

type Mutation struct {
}

type PermissionsGroup struct {
	Label string   `json:"label"`
	List  []string `json:"list"`
}

type PermissionsListReturn struct {
	Groups []*PermissionsGroup `json:"groups"`
}

type Query struct {
}

type Role struct {
	ID          string        `json:"Id"`
	Name        string        `json:"Name"`
	Permissions []string      `json:"Permissions,omitempty"`
	Settings    *RoleSettings `json:"Settings"`
}

type RoleSettings struct {
	Base bool `json:"base"`
}

type RoleSettingsDto struct {
	Base bool `json:"base"`
}
